# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR ORGANIZATION
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"POT-Creation-Date: 2019-04-08 13:55-0300\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=cp1252\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: pygettext.py 1.5\n"


#: core.py:43
msgid ""
"\n"
"    Error found in file '{filename}' on line {linenumber}.\n"
"\n"
"{partial_source}\n"
msgstr ""

#: core.py:105
msgid ""
"\n"
"    Execution stopped in file '{filename}' on line {linenumber}.\n"
"\n"
"{source}\n"
msgstr ""

#: core.py:113
msgid ""
"\n"
"    Exception raised in file '{filename}' on line {linenumber}.\n"
"\n"
"{source}\n"
msgstr ""

#: core.py:131
msgid ""
"\n"
"    Python exception: \n"
"        {name}: {value}\n"
"\n"
"{explanation}"
msgstr ""

#: core.py:145
msgid ""
"\n"
"    Likely cause: \n"
"{explanation}"
msgstr ""

#: generic_info.py:5
msgid ""
"    A NameError exception indicates that a variable or\n"
"    function name is not known to Python.\n"
"    Most often, this is because there is a spelling mistake.\n"
"    However, sometimes it is because the name is used\n"
"    before being defined or given a value.\n"
msgstr ""

#: generic_info.py:15
msgid ""
"    No information is known about this exception.\n"
msgstr ""

#: specific_info.py:10
msgid ""
"        In your program, the unknown name is '{var_name}'.\n"
msgstr ""

