
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Friendly tracebacks - en Français &#8212; Friendly tracebacks 0.0.3 documentation</title>
    <link rel="stylesheet" href="_static/sphinxdoc.css" type="text/css" />
    <link rel="stylesheet" href="_static/pygments.css" type="text/css" />
    <script type="text/javascript" id="documentation_options" data-url_root="./" src="_static/documentation_options.js"></script>
    <script type="text/javascript" src="_static/jquery.js"></script>
    <script type="text/javascript" src="_static/underscore.js"></script>
    <script type="text/javascript" src="_static/doctools.js"></script>
    <script type="text/javascript" src="_static/language_data.js"></script>
    <link rel="index" title="Index" href="genindex.html" />
    <link rel="search" title="Search" href="search.html" />
    <link rel="next" title="Notes on translations - using gettext" href="translation_notes.html" />
    <link rel="prev" title="Friendly tracebacks - in English" href="tracebacks_en.html" /> 
  </head><body>
    <div class="related" role="navigation" aria-label="related navigation">
      <h3>Navigation</h3>
      <ul>
        <li class="right" style="margin-right: 10px">
          <a href="genindex.html" title="General Index"
             accesskey="I">index</a></li>
        <li class="right" >
          <a href="translation_notes.html" title="Notes on translations - using gettext"
             accesskey="N">next</a> |</li>
        <li class="right" >
          <a href="tracebacks_en.html" title="Friendly tracebacks - in English"
             accesskey="P">previous</a> |</li>
        <li class="nav-item nav-item-0"><a href="index.html">Friendly tracebacks 0.0.3 documentation</a> &#187;</li> 
      </ul>
    </div>
      <div class="sphinxsidebar" role="navigation" aria-label="main navigation">
        <div class="sphinxsidebarwrapper">
  <h3><a href="index.html">Table of Contents</a></h3>
  <ul>
<li><a class="reference internal" href="#">Friendly tracebacks - en Français</a><ul>
<li><a class="reference internal" href="#indentationerror-1-expected-an-indented-block">IndentationError - 1: expected an indented block</a></li>
<li><a class="reference internal" href="#indentationerror-2-unexpected-indent">IndentationError - 2: unexpected indent</a></li>
<li><a class="reference internal" href="#indentationerror-3-unindent-does-not-match">IndentationError - 3: unindent does not match …</a></li>
<li><a class="reference internal" href="#nameerror">NameError</a></li>
<li><a class="reference internal" href="#unknown-exception">Unknown exception</a></li>
</ul>
</li>
</ul>

  <h4>Previous topic</h4>
  <p class="topless"><a href="tracebacks_en.html"
                        title="previous chapter">Friendly tracebacks - in English</a></p>
  <h4>Next topic</h4>
  <p class="topless"><a href="translation_notes.html"
                        title="next chapter">Notes on translations - using gettext</a></p>
  <div role="note" aria-label="source link">
    <h3>This Page</h3>
    <ul class="this-page-menu">
      <li><a href="_sources/tracebacks_fr.rst.txt"
            rel="nofollow">Show Source</a></li>
    </ul>
   </div>
<div id="searchbox" style="display: none" role="search">
  <h3>Quick search</h3>
    <div class="searchformwrapper">
    <form class="search" action="search.html" method="get">
      <input type="text" name="q" />
      <input type="submit" value="Go" />
      <input type="hidden" name="check_keywords" value="yes" />
      <input type="hidden" name="area" value="default" />
    </form>
    </div>
</div>
<script type="text/javascript">$('#searchbox').show(0);</script>
        </div>
      </div>

    <div class="document">
      <div class="documentwrapper">
        <div class="bodywrapper">
          <div class="body" role="main">
            
  <div class="section" id="friendly-tracebacks-en-francais">
<h1>Friendly tracebacks - en Français<a class="headerlink" href="#friendly-tracebacks-en-francais" title="Permalink to this headline">¶</a></h1>
<p>Le but principal de friendly-traceback est de fournir des rétroactions plus
conviviales que les fameux <strong>tracebacks</strong> de Python lorsqu’une exception survient.
Ci-dessous, on peut voir quelques exemples. Le but éventuel est de documenter
ici tous les exemples possibles tels qu’interprétés par friendly-traceback.</p>
<div class="admonition note">
<p class="first admonition-title">Note</p>
<p class="last">Le contenu de cette page a été généré par l’exécution de
tb_french.py situé dans le répertoire <code class="docutils literal notranslate"><span class="pre">tests/</span></code>.
Ceci a besoin d’être fait de manière explicite lorsqu’on veut
faire des corrections ou des ajouts, avant de faire la mise
à jour du reste de la documentation avec Sphinx.</p>
</div>
<p>Friendly-traceback version: 0.0.3
Python version: 3.7.0</p>
<div class="section" id="indentationerror-1-expected-an-indented-block">
<h2>IndentationError - 1: expected an indented block<a class="headerlink" href="#indentationerror-1-expected-an-indented-block" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Exception Python:
    IndentationError: expected an indented block (raise_indentation_error1.py, line 4)

Une exception de type IndentationError se produit lorsqu&#39;une ligne de code
n&#39;est pas indentée (c&#39;est-à-dire alignée verticalement avec les autres lignes)
de la façon attendue.

Cause probable :
    Python peut seulement analyser le fichier &#39;raise_indentation_error1.py&#39;
    jusqu&#39;à l&#39;endroit indiqué par --&gt; et ^.

   1: &#39;&#39;&#39;Should raise IndentationError&#39;&#39;&#39;
   2:
   3: if True:
--&gt;4: pass
         ^
    Dans ce cas-ci, la ligne indiquée ci-dessus par --&gt; devrait
    normalement commencer un nouveau bloc de code indenté.


L&#39;exécution s&#39;est arrêtée à la ligne 47 du fichier &#39;tb_common.py&#39;

   45:                 make_title(title)
   46:                 try:
--&gt;47:                     mod = __import__(name)
   48:                     if function is not None:
</pre></div>
</div>
</div>
<div class="section" id="indentationerror-2-unexpected-indent">
<h2>IndentationError - 2: unexpected indent<a class="headerlink" href="#indentationerror-2-unexpected-indent" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Exception Python:
    IndentationError: unexpected indent (raise_indentation_error2.py, line 4)

Une exception de type IndentationError se produit lorsqu&#39;une ligne de code
n&#39;est pas indentée (c&#39;est-à-dire alignée verticalement avec les autres lignes)
de la façon attendue.

Cause probable :
    Python peut seulement analyser le fichier &#39;raise_indentation_error2.py&#39;
    jusqu&#39;à l&#39;endroit indiqué par --&gt; et ^.

   1: &#39;&#39;&#39;Should raise IndentationError&#39;&#39;&#39;
   2: if True:
   3:     pass
--&gt;4:       pass
           ^
    Dans ce cas-ci, la ligne indiquée ci-dessus par --&gt;
    est plus indentée que ce qui était attendu et ne
    correspond pas à l&#39;indentation de la ligne précédente.


L&#39;exécution s&#39;est arrêtée à la ligne 47 du fichier &#39;tb_common.py&#39;

   45:                 make_title(title)
   46:                 try:
--&gt;47:                     mod = __import__(name)
   48:                     if function is not None:
</pre></div>
</div>
</div>
<div class="section" id="indentationerror-3-unindent-does-not-match">
<h2>IndentationError - 3: unindent does not match …<a class="headerlink" href="#indentationerror-3-unindent-does-not-match" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Exception Python:
    IndentationError: unindent does not match any outer indentation level (raise_indentation_error3.py, line 4)

Une exception de type IndentationError se produit lorsqu&#39;une ligne de code
n&#39;est pas indentée (c&#39;est-à-dire alignée verticalement avec les autres lignes)
de la façon attendue.

Cause probable :
    Python peut seulement analyser le fichier &#39;raise_indentation_error3.py&#39;
    jusqu&#39;à l&#39;endroit indiqué par --&gt; et ^.

   1: &#39;&#39;&#39;Should raise IndentationError&#39;&#39;&#39;
   2: if True:
   3:       pass
--&gt;4:     pass
              ^
    Dans ce cas-ci, la ligne indiquée ci-dessus par --&gt;
    est moins indentée que la ligne précédente
    et n’est pas alignée verticalement avec un autre bloc de code.


L&#39;exécution s&#39;est arrêtée à la ligne 47 du fichier &#39;tb_common.py&#39;

   45:                 make_title(title)
   46:                 try:
--&gt;47:                     mod = __import__(name)
   48:                     if function is not None:
</pre></div>
</div>
</div>
<div class="section" id="nameerror">
<h2>NameError<a class="headerlink" href="#nameerror" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Exception Python:
    NameError: name &#39;c&#39; is not defined

Une exception NameError indique que le nom d&#39;une variable
ou d&#39;une fonction n&#39;est pas connue par Python.
Habituellement, ceci indique une simple faute d&#39;orthographe.
Cependant, cela peut également indiquer que le nom a été
utilisé avant qu&#39;on ne lui ait associé une valeur.

Cause probable :
    Dans votre programme, le nom inconnu est &#39;c&#39;.


L&#39;exécution s&#39;est arrêtée à la ligne 49 du fichier &#39;tb_common.py&#39;

   47:                     mod = __import__(name)
   48:                     if function is not None:
--&gt;49:                         getattr(mod, function)()
   50:                 except Exception:


Exception levée à la ligne du fichier &#39;raise_name_error.py&#39;.

    6:     &quot;&quot;&quot;Should raise NameError&quot;&quot;&quot;
    7:     a = 1
--&gt; 8:     b = c
    9:     d = 3
</pre></div>
</div>
</div>
<div class="section" id="unknown-exception">
<h2>Unknown exception<a class="headerlink" href="#unknown-exception" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Exception Python:
    MyException: Some informative message

Aucune information n&#39;est connue au sujet de cette exception.


L&#39;exécution s&#39;est arrêtée à la ligne 49 du fichier &#39;tb_common.py&#39;

   47:                     mod = __import__(name)
   48:                     if function is not None:
--&gt;49:                         getattr(mod, function)()
   50:                 except Exception:


Exception levée à la ligne du fichier &#39;raise_unknown_error.py&#39;.

    6:
    7: def test():
--&gt; 8:     raise MyException(&quot;Some informative message&quot;)
    9:
</pre></div>
</div>
</div>
</div>


          </div>
        </div>
      </div>
      <div class="clearer"></div>
    </div>
    <div class="related" role="navigation" aria-label="related navigation">
      <h3>Navigation</h3>
      <ul>
        <li class="right" style="margin-right: 10px">
          <a href="genindex.html" title="General Index"
             >index</a></li>
        <li class="right" >
          <a href="translation_notes.html" title="Notes on translations - using gettext"
             >next</a> |</li>
        <li class="right" >
          <a href="tracebacks_en.html" title="Friendly tracebacks - in English"
             >previous</a> |</li>
        <li class="nav-item nav-item-0"><a href="index.html">Friendly tracebacks 0.0.3 documentation</a> &#187;</li> 
      </ul>
    </div>
    <div class="footer" role="contentinfo">
        &#169; Copyright 2019, André Roberge.
      Created using <a href="http://sphinx-doc.org/">Sphinx</a> 1.8.4.
    </div>
  </body>
</html>