# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR ORGANIZATION
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: \n"
"POT-Creation-Date: 2019-04-13 17:57-0300\n"
"PO-Revision-Date: 2019-04-13 18:03-0300\n"
"Last-Translator: André Roberge <andre.roberge@gmail.com>\n"
"Language-Team: \n"
"Language: fr\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: pygettext.py 1.5\n"
"X-Generator: Poedit 2.2.1\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"

#: formatter.py:21
msgid ""
"        Unfortunately, no additional information is available:\n"
"        the content of file '<string>' is not accessible.\n"
msgstr ""
"        Malheureusement, aucune information supplémentaire n’est "
"disponible:\n"
"        le contenu du fichier '<string>' n’est pas accessible.\n"

#: formatter.py:138
msgid ""
"\n"
"    Python exception: \n"
"        {name}: {value}\n"
"\n"
"{explanation}"
msgstr ""
"\n"
"    Exception Python: \n"
"        {name}: {value}\n"
"\n"
"{explanation}"

#: formatter.py:153
msgid ""
"    Likely cause:\n"
"{cause}"
msgstr ""
"    Cause probable : \n"
"{cause}"

#: formatter.py:175
msgid ""
"\n"
"    Execution stopped on line {linenumber} of file '{filename}'.\n"
"\n"
"{source}\n"
msgstr ""
"\n"
"    L'exécution s'est arrêtée à la ligne {linenumber} du fichier "
"'{filename}'\n"
"\n"
"{source}\n"

#: formatter.py:183
msgid ""
"\n"
"    Exception raised on line {linenumber} of file '{filename}'.\n"
"\n"
"{source}\n"
msgstr ""
"\n"
"    Exception levée à la ligne du fichier '{filename}'.\n"
"\n"
"{source}\n"

#: generic_info.py:7
msgid ""
"    An IndentationError occurs when a given line of code is\n"
"    not indented (aligned vertically with other lines) as expected.\n"
msgstr ""
"    Une exception de type IndentationError se produit lorsqu'une ligne de "
"code\n"
"    n'est pas indentée (c'est-à-dire alignée verticalement avec les autres "
"lignes)\n"
"    de la façon attendue.\n"

#: generic_info.py:15
msgid ""
"    A NameError exception indicates that a variable or\n"
"    function name is not known to Python.\n"
"    Most often, this is because there is a spelling mistake.\n"
"    However, sometimes it is because the name is used\n"
"    before being defined or given a value.\n"
msgstr ""
"    Une exception NameError indique que le nom d'une variable\n"
"    ou d'une fonction n'est pas connue par Python.\n"
"    Habituellement, ceci indique une simple faute d'orthographe.\n"
"    Cependant, cela peut également indiquer que le nom a été\n"
"    utilisé avant qu'on ne lui ait associé une valeur.\n"

#: generic_info.py:26
msgid ""
"    A SyntaxError occurs when Python cannot understand your code.\n"
"    There could be many possible reasons:\n"
"    - a keyword might be misspelled;\n"
"    - a colon, :, or some other symbol like (, ], etc., might be missing;\n"
"    - etc.\n"
msgstr ""
"    Une exception SyntaxError se produit lorsque python ne peut pas "
"comprendre votre code.\n"
"    Il pourrait y avoir plusieurs raisons possibles:\n"
"    - un mot-clé peut être mal orthographié;\n"
"    - le symbole deux points, :, ou un autre symbole comme (,], etc., "
"pourrait manquer;\n"
"    - etc.\n"

#: generic_info.py:37
msgid ""
"    A TabError indicates that you have used both spaces\n"
"    and tab characters to indent your code.\n"
"    This is not allowed in Python.\n"
"    Indenting your code means to have block of codes aligned vertically\n"
"    by inserting either spaces or tab characters at the beginning of lines.\n"
"    Python's recommendation is to always use spaces to indent your code.\n"
msgstr ""
"    Un exception de type TabError indique que vous avez utilisé des espaces "
"ainsi que\n"
"    des caractères de tabulation pour indenter votre code.\n"
"    Cela n’est pas autorisé dans Python.\n"
"    L’indentation de votre code signifie que le bloc de codes est aligné "
"verticalement \n"
"    en insérant des espaces ou des tabulations au début des lignes.\n"
"    La recommandation de Python est de toujours utiliser des espaces pour "
"indenter votre code.\n"

#: generic_info.py:49
msgid ""
"    In Python, variables that are used inside a function are known as \n"
"    local variables. Before they are used, they must be assigned a value.\n"
"    A variable that is used before it is assigned a value is assumed to\n"
"    be defined outside that function; it is known as a 'global'\n"
"    (or sometimes 'nonlocal') variable. You cannot assign a value to such\n"
"    a global variable inside a function without first indicating to\n"
"    Python that this is a global variable, otherwise you will see\n"
"    an UnboundLocalError.\n"
msgstr ""
"    En Python, les variables utilisées à l’intérieur d’une fonction sont "
"appelées variables «locales».\n"
"    Avant d’utiliser une variable locale, une valeur doit lui être "
"attribuée.\n"
"    Une variable utilisée avant l’attribution d’une valeur est supposée être "
"définie en\n"
"    dehors de cette fonction; elle est connu comme une variable "
"«globale» ('global' ou parfois 'nonlocal').\n"
"    Vous ne pouvez pas assigner une valeur à une telle variable globale à "
"l’intérieur d’une fonction\n"
"    sans d’abord confirmer à python qu’il s’agit d’une variable globale, "
"sinon vous verrez\n"
"    une exception UnboundLocalError.\n"

#: generic_info.py:63
msgid "    No information is known about this exception.\n"
msgstr "    Aucune information n'est connue au sujet de cette exception.\n"

#: generic_info.py:68
msgid ""
"    A ZeroDivisionError occurs when you are attempting to divide\n"
"    a value by zero:\n"
"        result = my_variable / 0\n"
"    It can also happen if you calculate the remainder of a division\n"
"    using the modulo operator '%'\n"
"        result = my_variable % 0"
msgstr ""
"    Une exception de type ZeroDivisionError se produit lorsque\n"
"    vous tentez de diviser une valeur par zéro:\n"
"        résultat = ma_variable / 0\n"
"    Ceci peut également se produire si vous calculez le reste d’une "
"division \n"
"    à l’aide de l’opérateur modulo '%'\n"
"        résultat = ma_variable % 0"

#: specific_info.py:21 specific_info.py:69 specific_info.py:91
msgid ""
"        Python could not parse the file '{filename}'\n"
"        beyond the location indicated below by --> and ^.\n"
"\n"
"{source}\n"
msgstr ""
"        Python peut seulement analyser le fichier '{filename}'\n"
"        jusqu'à l'endroit indiqué par --> et ^.\n"
"\n"
"{source}\n"

#: specific_info.py:30
msgid ""
"        In this case, the line identified above\n"
"        is more indented than expected and \n"
"        does not match the indentation of the previous line.\n"
msgstr ""
"        Dans ce cas-ci, la ligne indiquée ci-dessus par -->\n"
"        est plus indentée que ce qui était attendu et ne\n"
"        correspond pas à l'indentation de la ligne précédente.\n"

#: specific_info.py:36
msgid ""
"        In this case, the line identified above\n"
"        was expected to begin a new indented block.\n"
msgstr ""
"        Dans ce cas-ci, la ligne indiquée ci-dessus par --> devrait\n"
"        normalement commencer un nouveau bloc de code indenté.\n"

#: specific_info.py:41
msgid ""
"        In this case, the line identified above is\n"
"        less indented than the preceding one,\n"
"        and is not aligned vertically with another block of code.\n"
msgstr ""
"        Dans ce cas-ci, la ligne indiquée ci-dessus par -->\n"
"        est moins indentée que la ligne précédente\n"
"        et n’est pas alignée verticalement avec un autre bloc de code.\n"

#: specific_info.py:56
msgid "        In your program, the unknown name is '{var_name}'.\n"
msgstr "        Dans votre programme, le nom inconnu est '{var_name}'.\n"

#: specific_info.py:106
msgid ""
"        The variable that appears to cause the problem is '{var_name}'.\n"
"        Try inserting the statement\n"
"            global {var_name}\n"
"        as the first line inside your function."
msgstr ""
"        La variable qui semble causer le problème est' {var_name} '.\n"
"        Essayez d’insérer l’instruction\n"
"            global {var_name}\n"
"        comme première ligne à l’intérieur de votre fonction."

#: specific_info.py:132
msgid ""
"        My best guess: you were trying to assign a value\n"
"        to a Python keyword. This is not allowed.\n"
"\n"
msgstr ""
"        Ma meilleure hypothèse: vous essayiez d’assigner une valeur à un mot "
"clé Python.\n"
"        Ceci n’est pas permis.\n"
"\n"

#: specific_info.py:139
msgid ""
"       My best guess: you wanted to define a class but\n"
"       forgot to add a colon ':' at the end\n"
"\n"
msgstr ""
"        Ma meilleure hypothèse: vous vouliez définir une classe,\n"
"        mais vous avez oublié d’ajouter deux points ':' à la fin.\n"
"\n"

#: specific_info.py:146
msgid ""
"       My best guess: you wanted to define a function but\n"
"       forgot to add a colon ':' at the end\n"
"\n"
msgstr ""
"        Ma meilleure hypothèse: vous vouliez définir une fonction,\n"
"        mais vous avez oublié d’ajouter deux points ':' à la fin.\n"
"\n"

#: specific_info.py:153
msgid ""
"       My best guess: you wrote an elif statement but\n"
"       forgot to add a colon ':' at the end\n"
"\n"
msgstr ""
"        Ma meilleure hypothèse: vous avez écrit un énoncé 'elif'\n"
"        mais vous avez oublié d’ajouter deux points ':' à la fin.\n"
"\n"

#: specific_info.py:160
msgid ""
"       My best guess: you wrote an else statement but\n"
"       forgot to add a colon ':' at the end\n"
"\n"
msgstr ""
"        Ma meilleure hypothèse: vous avez écrit un énoncé 'else'\n"
"        mais vous avez oublié d’ajouter deux points ':' à la fin.\n"
"\n"

#: specific_info.py:167
msgid ""
"       My best guess: you wrote a finally statement but\n"
"       forgot to add a colon ':' at the end\n"
"\n"
msgstr ""
"        Ma meilleure hypothèse: vous avez écrit un énoncé 'finally'\n"
"        mais vous avez oublié d’ajouter deux points ':' à la fin.\n"
"\n"

#: specific_info.py:174
msgid ""
"       My best guess: you wrote a for loop but\n"
"       forgot to add a colon ':' at the end\n"
"\n"
msgstr ""
"        Ma meilleure hypothèse: vous vouliez débuter une boucle 'for'\n"
"        mais vous avez oublié d’ajouter deux points ':' à la fin.\n"
"\n"

#: specific_info.py:181
msgid ""
"       My best guess: you wrote an if statement but\n"
"       forgot to add a colon ':' at the end\n"
"\n"
msgstr ""
"        Ma meilleure hypothèse: vous avez écrit un énoncé 'if'\n"
"        mais vous avez oublié d’ajouter deux points ':' à la fin.\n"
"\n"

#: specific_info.py:188
msgid ""
"       My best guess: you wrote a while loop but\n"
"       forgot to add a colon ':' at the end\n"
"\n"
msgstr ""
"        Ma meilleure hypothèse: vous vouliez débuter une boucle 'while'\n"
"        mais vous avez oublié d’ajouter deux points ':' à la fin.\n"
"\n"

#: specific_info.py:194
msgid ""
"        Currently, we cannot give you more information\n"
"        about the likely cause of this error.\n"
"\n"
msgstr ""
"        Actuellement, nous ne pouvons pas vous donner plus d’informations\n"
"        sur la cause probable de cette erreur.\n"
"\n"

#~ msgid "Cannot find source code."
#~ msgstr "Impossible de trouver la source du code."

#~ msgid ""
#~ "\n"
#~ "    Error found in file '{filename}' on line {linenumber}.\n"
#~ "\n"
#~ "{partial_source}\n"
#~ msgstr ""
#~ "\n"
#~ "    Erreur trouvée dans le fichier '{filename}' à la ligne {linenumber}.\n"
#~ "\n"
#~ "{partial_source}\n"
